import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, ExternalLink, TrendingUp, AlertCircle, Lightbulb, Calendar, ChevronDown, ChevronUp } from "lucide-react";

const DATE = new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"});

const BRIEFING = {
  headline: "Three high-leverage opportunities in your authority zone this week.",
  generated: "Generated by Sentinel · 6:02 AM",
};

type Strength = "high"|"medium"|"low";
type Category = "Opportunity"|"Gap"|"Momentum"|"Timing"|"Threat";
interface Signal {
  id: number;
  category: Category;
  strength: Strength;
  headline: string;
  detail: string;
  sources: string[];
  angle?: string;
  score: number;
}

const SIGNALS: Signal[] = [
  {
    id:1, category:"Opportunity", strength:"high",
    headline:"AI leadership content spiked 38% engagement this week",
    detail:"Across LinkedIn, Substack, and X, long-form content about AI's impact on leadership decision-making is outperforming category averages by 38%. The conversations skewing highest: 'how to lead teams through AI transitions' and 'what AI can't replace in leadership.' Your existing authority in quiet leadership positions you directly in this window.",
    sources:["LinkedIn Content Analytics","Substack Trending","Beehiiv Industry Report"],
    angle:"Essay: 'What AI reveals about the leaders it can't replace' — 3 hooks mapped, ready to brief.",
    score:91,
  },
  {
    id:2, category:"Gap", strength:"high",
    headline:"Competitor published on burnout — left the 'recovery' angle open",
    detail:"TK Coleman published a widely-shared piece on burnout prevention yesterday. It performed well (4.2K engagements) but didn't touch recovery — what to do once you're already burned out. That's an unaddressed adjacent. Your 'slow thinking' framework maps directly into this gap.",
    sources:["Competitor Monitor","Google Alerts: burnout + leadership"],
    angle:"LinkedIn Post series: 'After the burnout: a 4-stage recovery map' — builds on your existing framework.",
    score:84,
  },
  {
    id:3, category:"Momentum", strength:"medium",
    headline:"Your 'delegation' essay gaining traction in SB entrepreneur circles",
    detail:"3 reposts from Santa Barbara Business Journal readers, 2 newsletter citations, and a mention in the Coastal Intelligence podcast this week. The essay is building organic momentum 6 weeks after publishing — which suggests this topic has longer legs. Could anchor a talk or book chapter.",
    sources:["Google Alerts: 'Mark Sylvester'","LinkedIn mentions","Email digest scans"],
    angle:"Consider: a talk outline version of this essay for your next speaking engagement.",
    score:72,
  },
  {
    id:4, category:"Timing", strength:"medium",
    headline:"Tuesday 7am is your peak audience window — you're currently posting Thursday",
    detail:"Cross-referencing your past 30 LinkedIn posts against engagement data: content published Tuesday between 6:30–8:00am PT receives 2.1x the engagement of Thursday content. Your current default schedule is Thursday 9am. A simple shift could significantly amplify the same content.",
    sources:["LinkedIn Analytics","Historical post performance"],
    angle:"No new content needed — reschedule next 3 posts to Tuesday 7am PT.",
    score:68,
  },
  {
    id:5, category:"Threat", strength:"low",
    headline:"Two new voices entering your 'quiet leadership' niche",
    detail:"Priya Iyer (42K LinkedIn followers) and James Forrest (newsletter: 18K) both published 'quiet leader' content in the past 10 days. Early engagement suggests audience overlap with yours. Not an immediate threat, but worth monitoring. Your differentiation is lived-in specificity — they're still pattern-matching.",
    sources:["LinkedIn Competitor Monitor","Substack Trending"],
    score:45,
  },
];

const CATEGORY_COLOR: Record<Category, string> = {
  Opportunity:"#4A90D9", Gap:"#F5C642", Momentum:"#188FA7", Timing:"#9B7ECC", Threat:"#DC4444",
};
const STRENGTH_LABEL: Record<Strength, string> = { high:"HIGH SIGNAL", medium:"MED SIGNAL", low:"LOW SIGNAL" };

function SignalCard({ signal }: { signal: Signal }) {
  const [open, setOpen] = useState(signal.strength === "high");
  const col = CATEGORY_COLOR[signal.category];

  return (
    <div style={{ background:"var(--bg-secondary)", border:"1px solid var(--border)",
      borderLeft:`3px solid ${col}`, borderRadius:10, overflow:"hidden", marginBottom:12 }}>
      {/* Header row */}
      <div style={{ padding:"18px 20px", cursor:"pointer", display:"flex", alignItems:"flex-start", gap:14 }}
        onClick={() => setOpen(o => !o)}>
        <div style={{ flex:1 }}>
          <div style={{ display:"flex", gap:8, alignItems:"center", marginBottom:6, flexWrap:"wrap" }}>
            <span style={{ fontSize:10, fontWeight:700, letterSpacing:"0.10em", textTransform:"uppercase",
              color:col, fontFamily:"'Afacad Flux',sans-serif" }}>{signal.category}</span>
            <span style={{ fontSize:9, letterSpacing:"0.08em", textTransform:"uppercase",
              color:"var(--text-muted)", fontFamily:"'Afacad Flux',sans-serif",
              background:"var(--bg-tertiary)", padding:"2px 7px", borderRadius:3,
              fontWeight:600 }}>{STRENGTH_LABEL[signal.strength]}</span>
            {/* Fish score */}
            <span style={{ fontSize:10, color:"var(--text-muted)", fontFamily:"'Afacad Flux',sans-serif",
              marginLeft:"auto" }}>
              Fish: <span style={{ fontWeight:700, color:signal.score>=80?col:"var(--text-secondary)" }}>
                {signal.score}/100
              </span>
            </span>
          </div>
          <p style={{ fontSize:15, fontWeight:600, color:"var(--text-primary)",
            fontFamily:"'Afacad Flux',sans-serif", letterSpacing:"-.02em", lineHeight:1.35 }}>
            {signal.headline}
          </p>
        </div>
        <div style={{ color:"var(--text-muted)", flexShrink:0, marginTop:2 }}>
          {open ? <ChevronUp size={15}/> : <ChevronDown size={15}/>}
        </div>
      </div>

      {/* Expanded detail */}
      {open && (
        <div style={{ padding:"0 20px 20px", borderTop:"1px solid var(--border)" }}>
          <p style={{ fontSize:13, color:"var(--text-secondary)", lineHeight:1.7,
            fontFamily:"'Afacad Flux',sans-serif", marginTop:16, marginBottom:14 }}>
            {signal.detail}
          </p>

          {/* Sources */}
          <div style={{ display:"flex", gap:8, flexWrap:"wrap", marginBottom:14 }}>
            {signal.sources.map(s => (
              <span key={s} style={{ fontSize:10, padding:"3px 9px", borderRadius:4,
                background:"var(--bg-primary)", border:"1px solid var(--border)",
                color:"var(--text-muted)", fontFamily:"'Afacad Flux',sans-serif",
                display:"flex", alignItems:"center", gap:4 }}>
                <ExternalLink size={9} /> {s}
              </span>
            ))}
          </div>

          {/* Angle suggestion */}
          {signal.angle && (
            <div style={{ padding:"12px 14px", background:`${col}0d`, border:`1px solid ${col}28`,
              borderRadius:7, display:"flex", alignItems:"flex-start", gap:10 }}>
              <Lightbulb size={13} style={{ color:col, flexShrink:0, marginTop:1 }} />
              <div>
                <span style={{ fontSize:10, fontWeight:700, letterSpacing:"0.08em",
                  textTransform:"uppercase", color:col, fontFamily:"'Afacad Flux',sans-serif",
                  display:"block", marginBottom:3 }}>Suggested Angle</span>
                <p style={{ fontSize:12, color:"var(--text-secondary)", fontFamily:"'Afacad Flux',sans-serif",
                  lineHeight:1.55 }}>{signal.angle}</p>
              </div>
            </div>
          )}

          {/* Action */}
          <button style={{ marginTop:14, display:"inline-flex", alignItems:"center", gap:7,
            background:"var(--text-primary)", color:"var(--bg-primary)", border:"none",
            borderRadius:6, padding:"9px 16px", cursor:"pointer", fontSize:12, fontWeight:700,
            fontFamily:"'Afacad Flux',sans-serif", letterSpacing:"-.01em", transition:"opacity .15s" }}
            onMouseEnter={e=>(e.currentTarget.style.opacity=".8")} onMouseLeave={e=>(e.currentTarget.style.opacity="1")}>
            Write from this signal <ArrowRight size={12} />
          </button>
        </div>
      )}
    </div>
  );
}

export default function Watch() {
  const [activeFilter, setActiveFilter] = useState<"All"|Category>("All");
  const filters: ("All"|Category)[] = ["All","Opportunity","Gap","Momentum","Timing","Threat"];

  const filtered = activeFilter === "All" ? SIGNALS : SIGNALS.filter(s => s.category === activeFilter);

  return (
    <div style={{ padding:"44px 40px 80px", maxWidth:860, margin:"0 auto" }}>
      {/* Header */}
      <div style={{ marginBottom:36 }}>
        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:10 }}>
          <div>
            <p style={{ fontSize:12, color:"var(--text-muted)", fontFamily:"'Afacad Flux',sans-serif",
              letterSpacing:"0.06em", textTransform:"uppercase", marginBottom:4 }}>
              Watch · {DATE}
            </p>
            <h1 style={{ fontSize:"clamp(24px,3vw,36px)", fontWeight:800, color:"var(--text-primary)",
              letterSpacing:"-.04em", fontFamily:"'Afacad Flux',sans-serif", lineHeight:1, marginBottom:8 }}>
              {BRIEFING.headline}
            </h1>
            <p style={{ fontSize:11, color:"var(--text-muted)", fontFamily:"'Afacad Flux',sans-serif" }}>
              {BRIEFING.generated}
            </p>
          </div>
          <div style={{ display:"flex", alignItems:"center", gap:6, padding:"6px 12px",
            background:"rgba(24,143,167,.08)", border:"1px solid rgba(24,143,167,.2)", borderRadius:6 }}>
            <span style={{ width:6, height:6, borderRadius:"50%", background:"#188FA7",
              boxShadow:"0 0 8px rgba(24,143,167,.8)", display:"block" }} />
            <span style={{ fontSize:11, color:"#188FA7", fontWeight:600,
              fontFamily:"'Afacad Flux',sans-serif" }}>Sentinel Active</span>
          </div>
        </div>
      </div>

      {/* Filter pills */}
      <div style={{ display:"flex", gap:8, flexWrap:"wrap", marginBottom:24 }}>
        {filters.map(f => (
          <button key={f} onClick={() => setActiveFilter(f)}
            style={{ padding:"6px 14px", borderRadius:100, border:"1px solid",
              borderColor:activeFilter===f?(f==="All"?"var(--border-strong)":CATEGORY_COLOR[f as Category]):"var(--border)",
              background:activeFilter===f?"var(--bg-secondary)":"transparent",
              color:activeFilter===f?(f==="All"?"var(--text-primary)":CATEGORY_COLOR[f as Category]):"var(--text-muted)",
              cursor:"pointer", fontSize:12, fontWeight:500,
              fontFamily:"'Afacad Flux',sans-serif", transition:"all .15s", letterSpacing:"-.01em" }}>
            {f} {f!=="All" && `(${SIGNALS.filter(s=>s.category===f).length})`}
          </button>
        ))}
      </div>

      {/* Signal cards */}
      {filtered.map(s => <SignalCard key={s.id} signal={s} />)}

      {/* Weekly calendar hint */}
      <div style={{ marginTop:32, padding:"18px 20px", background:"var(--bg-secondary)",
        border:"1px solid var(--border)", borderRadius:10, display:"flex", gap:12, alignItems:"center" }}>
        <Calendar size={16} style={{ color:"var(--text-muted)", flexShrink:0 }} />
        <div>
          <p style={{ fontSize:13, fontWeight:600, color:"var(--text-primary)",
            fontFamily:"'Afacad Flux',sans-serif", marginBottom:2, letterSpacing:"-.02em" }}>
            Next briefing: Tomorrow, 6:00 AM
          </p>
          <p style={{ fontSize:11, color:"var(--text-muted)", fontFamily:"'Afacad Flux',sans-serif" }}>
            Sentinel runs daily. Configure topics and frequency in Settings.
          </p>
        </div>
      </div>
    </div>
  );
}
